# Server Configuration
server.port=8080

# Externalized Configuration
spring.config.import=optional:classpath:/config/application-local.properties

# Logging Configuration
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.cl.camodev.wosbot=INFO
logging.level.cl.camodev.wosbot.almac.jpa.BotPersistence=DEBUG

# Developer Tooling
spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-paths=src/main/resources/static
spring.devtools.restart.exclude=static/**,public/**

# Web Streaming
spring.mvc.async.request-timeout=-1

# Spring Boot Banner
spring.main.banner-mode=off

# Project Version (for VersionApi)
project.version=@project.version@
